import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MainHeader } from '@/components/welcome/MainHeader'
import CursorFollower from '@/components/CursorFollower'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${inter.variable} font-sans antialiased max-w-[1920px] relative mx-auto px-4 bg-[#0A0A0A]`}
      >
        <MainHeader />
        <CursorFollower />
        {children}
      </body>
    </html>
  )
}
